name: Mi workflow

on:
  push:
    branches:
      - main # Puedes especificar aquí la rama en la que quieres que se active el flujo

jobs:
  tareas:
    runs-on: ubuntu-latest
    steps:
      - name: Bajar código
        uses: actions/checkout@v4

      - name: Probar código
        run: python3 main.py

      - name: Crear imagen Docker
        run: docker build -t Alvaroguerricagoitia/holamundo .

      - name: Probar imagen
        run: docker run Alvaroguerricagoitia/holamundo
